- id: kubeseal-secrets
  name: Kubeseal secrets files
  entry: python3 ./kubeseal-secrets.py
  language: python
  args:
    - "*secret*"
  description: |
    Finds secret files matching the pattern and creates sealed secrets using kubeseal.
  stages: [commit]
  pass_filenames: false
