name: Create Release and update README

on:
  push:
    tags:
      - "*.*.*"
      - "*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Get current tag name
        id: current_tag
        run: echo "current_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Get previous tag
        id: previous_tag
        run: |
          git fetch --tags
          mapfile -t tags < <(git tag --sort=-v:refname)
          current_index=-1
          for i in "${!tags[@]}"; do
            if [[ "${tags[i]}" == "${{ env.current_tag }}" ]]; then
              current_index=$i
              break
            fi
          done
          if (( current_index > 0 )); then
            echo "previous_tag=${tags[current_index-1]}" >> $GITHUB_ENV
          else
            echo "previous_tag=" >> $GITHUB_ENV
          fi

      - name: Show tags
        run: |
          echo "Current tag: ${{ env.current_tag }}"
          echo "Previous tag: ${{ env.previous_tag }}"

      - name: Update README with new tag
        shell: bash
        run: |
          python -c "
          import re
          current_tag = '${{ env.current_tag }}'
          with open('README.md', 'r') as f:
              content = f.read()
          new_content = re.sub(
              r'(rev:\s*)[\w\.\-]+',
              lambda m: m.group(1) + current_tag,
              content
          )
          with open('README.md', 'w') as f:
              f.write(new_content)
          print('Updated README with current tag revision')
          "

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push README update
        run: |
          git add README.md
          git commit -m "chore: update rev tag to ${{ env.current_tag }} in README"
          git push origin main

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.current_tag }}
          release_name: ${{ env.current_tag }}
          body: | 
            See: https://github.com/${{ github.repository }}/compare/${{ env.previous_tag }}...${{ env.current_tag }}
